//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace prjDAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ZamaniEntities : DbContext
    {
        public ZamaniEntities()
            : base("name=ZamaniEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tblClasses> tblClasses { get; set; }
        public virtual DbSet<tblPayments> tblPayments { get; set; }
        public virtual DbSet<tblStudents> tblStudents { get; set; }
    }
}
