//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace prjDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblStudents
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblStudents()
        {
            this.tblPayments = new HashSet<tblPayments>();
        }
    
        public int StdId { get; set; }
        public string CodeMeli { get; set; }
        public string FName { get; set; }
        public string LName { get; set; }
        public string TarikhTavalod { get; set; }
        public string FatherName { get; set; }
        public string MotherName { get; set; }
        public Nullable<int> ClassId { get; set; }
    
        public virtual tblClasses tblClasses { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblPayments> tblPayments { get; set; }
    }
}
